audit_header: false
title: Hayward Real Estate Video Blog with Jose Diaz
description: Our mission at Fohl & Hernandez Real Estate is to be your best resource for Hayward real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Fohl & Hernandez Real Estate, your professional Hayward Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Jose Diaz
  title:
  license_number:
  about_markdown: |
    I am a licensed Real Estate Broker. I specialize in representing my clients in the purchase and sale of single-family residences and income property within Hayward and the East Bay. I truly love this area and pride myself on my knowledge of current transactions, school districts, neighborhood information, and related services, including mortgage, insurance and inspection information.

    I am a customer driven Realtor dedicated to achieving results and providing exceptional service. If you are in the market to buy or sell a home, I will put my 25 years of real estate expertise to work for you!
  brand: Fohl & Hernandez Real Estate
  brokerage:
  market: Hayward
  address: 22326 Main St - Hayward, CA 94541
  phone: 510-912-4519
  phone_type:
  phone2:
  phone2_type:
  email: jd4realtor@gmail.com
  url: https://www.jdiazrealtors.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://jdrealtor.marketanalysis.report/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.jdiazrealtors.com/advanced-search

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Hayward Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://jdrealtor.marketanalysis.report/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Hayward Home?"
    CTA_text2: "Search the entire MLS for your Hayward home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.jdiazrealtors.com/advanced-search

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/jdiazrealtors
  linkedin_url: https://www.linkedin.com/in/jdiazrealtors/
  youtube_url: http://youtube.com/channel/UCaJ44--eHHW5fQRG38rKqMQ?view_as=subscriber
  twitter_url: https://twitter.com/JDiazRealtors
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Hayward Real Estate Podcast with Jose Diaz'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Hayward Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Fohl & Hernandez Real Estate - your professional Hayward Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Hayward, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jose Diaz'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Hayward Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
